version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    restart: always
  db:
    image: postgres:10-alpine
    container_name: postgresql
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://db_user:db_password@db:5432/postgres?sslmode=disable
