version: '2'
services:
  plane:
    image: 933714115463.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:latest
    container_name: plane
    volumes:
      - ../plane:/var/www
    restart: always
    depends_on:
      - db
      - nginx
  laravel:
    image: 933714115463.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:latest
    container_name: laravel
    volumes:
      - ../laravel:/var/www
    restart: always
    depends_on:
      - db
      - nginx
  ethnam:
    image: 933714115463.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:latest
    container_name: ethnam
    volumes:
      - ../ethnam:/var/www
    restart: always
    depends_on:
      - db
      - nginx
  yeahcheese:
    image: 933714115463.dkr.ecr.ap-northeast-1.amazonaws.com/php-fpm:latest
    container_name: yeahcheese
    volumes:
      - ../yeahcheese:/var/www
    restart: always
    depends_on:
      - db
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/ssl/
      - ../:/var/www
    restart: always
  db:
    image: postgres:10-alpine
    container_name: postgresql
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis:/data
    restart: always
