version: '2'
services:
  php:
    build: ./php-fpm
    container_name: php
    volumes:
      - ../laravel:/var/laravel:cached
    restart: always
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    restart: always
  db:
    image: postgres:10-alpine
    container_name: postgresql
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./reis:/data
    restart: always
